### ISSUE TITLE
default username and pwd does not work

### ISSUE THREAD

**Issue by Shanfang** [sitepoint-editors/angular-todo-app#5]

**Comment by jvandemo** [comment]
Are you running `json-server.js` of the `feat/part-5` branch?

The username and password are defined on line 22: https://github.com/sitepoint-editors/angular-todo-app/blob/feat/part-5/json-server.js#L22.

Obviously, for a real implementation, the username and password would not be hardcoded.

I'll close the issue because part 5 of the series has not been published yet, but feel free to re-open if needed. Thanks!

**Comment by Shanfang** [comment]
Thanks, I did not notice that and just tried to play with part-5. I am looking forward to see publication of that part.

**Comment by jvandemo** [comment]
@Shanfang &mdash; My pleasure, thank you for your kind feedback. Much appreciated!
